#!/usr/bin/env python
# Author: John Hawkins (jsh) [really@gmail.com]

import argparse
import logging
import pathlib
import sys

import pandas as pd

import gamma_lib as gl
import model_lib as ml

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s %(levelname)s %(message)s')

_PACKAGEDIR = pathlib.Path(__file__).parent
TESTDIR = _PACKAGEDIR / 'testdata'

def parse_args():
  """Read in the arguments for the sgrna library construction code."""
  logging.info('Parsing command line.')
  parser = argparse.ArgumentParser(
      formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument(
      '--genbank', type=str,
      help='file: base genome for organism in genbank format',
      default=str(TESTDIR / 'bsu.NC_000964.merged.gb'))
  parser.add_argument( # TODO(jsh): can probably ditch this and lose offset
      '--annofile', type=str,
      help='file: ???.targets.all.tsv (as generated by traeki/sgrna_design)',
      default=str(TESTDIR / 'test.gb.targets.all.tsv'))
  parser.add_argument(
      '--predfile', type=str,
      help='file: prediction-scored table created by choose_guides.py',
      default=str(TESTDIR / 'test.chosen.guides.tsv'))
  parser.add_argument(
      '--controls', type=str,
      help='file: list of just control guides',
      default=str(TESTDIR / 'control.guidepool'))
  parser.add_argument( # TODO(jsh): this is redundant with predfile/controls
      '--config', type=str,
      help='file: configuration table with...\nREPL\tSTART\tEND\n...entries.',
      default=str(TESTDIR / 'test.gamma.config.tsv'))
  parser.add_argument( # TODO(jsh): this is redundant with predfile/controls
      '--gammafile', type=str,
      help='file: file to which to write annotated gamma measurements',
      default=None)
  parser.add_argument(
      '--growth', type=int,
      help='int: number of generations grown (in other words, g*t)',
      default=10)
  args = parser.parse_args()
  if args.gammafile is None:
    args.gammafile = pathlib.Path(args.predfile).with_suffix('.gammas.tsv')
  return args


def flatgamma(stacked_replicates):
  data = stacked_replicates
  data['y_pred'] = -(ml.predict_mismatch_scores(data))
  anno = data.drop(['rep', 'gamma', 'start_mask'], axis='columns')
  anno = anno.drop_duplicates()
  gamma = data[['variant', 'rep', 'gamma']].set_index(['variant', 'rep'])
  gamma = gamma.unstack(level='rep').mean(axis='columns')
  data = pd.DataFrame(anno)
  data.set_index('variant', inplace=True)
  data['gamma'] = gamma
  return data


def main():
  args = parse_args()
  controls = set(pd.read_csv(args.controls, header=None))
  config = pd.read_csv(args.config, sep='\t')
  config = config.set_index('sample')
  rep_frames = list()
  for rep, ends in config.iterrows():
    logging.info('Computing gammas for sample {rep}...'.format(**locals()))
    rep_frame = gl.compute_gamma(ends.start, ends.end, controls, args.growth)
    rep_frame['rep'] = rep
    rep_frame = rep_frame.reset_index()
    rep_frames.append(rep_frame)
  collected = pd.concat(rep_frames).reset_index(drop=True)
  variants = collected.variant
  annoframe = gl.annotate_variants(variants,
                                   args.predfile,
                                   args.annofile,
                                   args.genbank)
  annoframe = annoframe.drop('variant', axis='columns')
  annoframe = pd.concat([collected, annoframe], axis='columns')
  annoframe.to_csv(args.gammafile, index=False, sep='\t')
  flatframe = flatgamma(annoframe)
  flatfile = pathlib.Path(args.gammafile).with_suffix('.mean.tsv')
  flatframe.to_csv(flatfile, sep='\t')

##############################################
if __name__ == "__main__":
  sys.exit(main())
